
insert into `state`(`state_id`,`state_cd`,`name_txt`) values (1,'AL','Alabama');
insert into `state`(`state_id`,`state_cd`,`name_txt`) values (2,'AK','Alaska');
insert into `state`(`state_id`,`state_cd`,`name_txt`) values (3,'AZ','Arizona');
insert into `state`(`state_id`,`state_cd`,`name_txt`) values (4,'AR','Arkansas');
insert into `state`(`state_id`,`state_cd`,`name_txt`) values (5,'CA','California');
insert into `state`(`state_id`,`state_cd`,`name_txt`) values (6,'CO','Colorado');
insert into `state`(`state_id`,`state_cd`,`name_txt`) values (7,'CT','Connecticut');
insert into `state`(`state_id`,`state_cd`,`name_txt`) values (8,'DE','Delaware');
insert into `state`(`state_id`,`state_cd`,`name_txt`) values (9,'DC','District of Columbia');
insert into `state`(`state_id`,`state_cd`,`name_txt`) values (10,'FL','Florida');
insert into `state`(`state_id`,`state_cd`,`name_txt`) values (11,'GA','Georgia');
insert into `state`(`state_id`,`state_cd`,`name_txt`) values (12,'HI','Hawaii');
insert into `state`(`state_id`,`state_cd`,`name_txt`) values (13,'ID','Idaho');
insert into `state`(`state_id`,`state_cd`,`name_txt`) values (14,'IL','Illinois');
insert into `state`(`state_id`,`state_cd`,`name_txt`) values (15,'IN','Indiana');
insert into `state`(`state_id`,`state_cd`,`name_txt`) values (16,'IA','Iowa');
insert into `state`(`state_id`,`state_cd`,`name_txt`) values (17,'KS','Kansas');
insert into `state`(`state_id`,`state_cd`,`name_txt`) values (18,'KY','Kentucky');
insert into `state`(`state_id`,`state_cd`,`name_txt`) values (19,'LA','Louisiana');
insert into `state`(`state_id`,`state_cd`,`name_txt`) values (20,'ME','Maine');
insert into `state`(`state_id`,`state_cd`,`name_txt`) values (21,'MD','Maryland');
insert into `state`(`state_id`,`state_cd`,`name_txt`) values (22,'MA','Massachusetts');
insert into `state`(`state_id`,`state_cd`,`name_txt`) values (23,'MI','Michigan');
insert into `state`(`state_id`,`state_cd`,`name_txt`) values (24,'MN','Minnesota');
insert into `state`(`state_id`,`state_cd`,`name_txt`) values (25,'MS','Mississippi');
insert into `state`(`state_id`,`state_cd`,`name_txt`) values (26,'MO','Missouri');
insert into `state`(`state_id`,`state_cd`,`name_txt`) values (27,'MT','Montana');
insert into `state`(`state_id`,`state_cd`,`name_txt`) values (28,'NE','Nebraska');
insert into `state`(`state_id`,`state_cd`,`name_txt`) values (29,'NV','Nevada');
insert into `state`(`state_id`,`state_cd`,`name_txt`) values (30,'NH','New Hampshire');
insert into `state`(`state_id`,`state_cd`,`name_txt`) values (31,'NJ','New Jersey');
insert into `state`(`state_id`,`state_cd`,`name_txt`) values (32,'NM','New Mexico');
insert into `state`(`state_id`,`state_cd`,`name_txt`) values (33,'NY','New York');
insert into `state`(`state_id`,`state_cd`,`name_txt`) values (34,'NC','North Carolina');
insert into `state`(`state_id`,`state_cd`,`name_txt`) values (35,'ND','North Dakota');
insert into `state`(`state_id`,`state_cd`,`name_txt`) values (36,'OH','Ohio');
insert into `state`(`state_id`,`state_cd`,`name_txt`) values (37,'OK','Oklahoma');
insert into `state`(`state_id`,`state_cd`,`name_txt`) values (38,'OR','Oregon');
insert into `state`(`state_id`,`state_cd`,`name_txt`) values (39,'PA','Pennsylvania');
insert into `state`(`state_id`,`state_cd`,`name_txt`) values (40,'PR','Puerto Rico');
insert into `state`(`state_id`,`state_cd`,`name_txt`) values (41,'RI','Rhode Island');
insert into `state`(`state_id`,`state_cd`,`name_txt`) values (42,'SC','South Carolina');
insert into `state`(`state_id`,`state_cd`,`name_txt`) values (43,'SD','South Dakota');
insert into `state`(`state_id`,`state_cd`,`name_txt`) values (44,'TN','Tennesee');
insert into `state`(`state_id`,`state_cd`,`name_txt`) values (45,'TX','Texas');
insert into `state`(`state_id`,`state_cd`,`name_txt`) values (46,'UT','Utah');
insert into `state`(`state_id`,`state_cd`,`name_txt`) values (47,'VT','Vermont');
insert into `state`(`state_id`,`state_cd`,`name_txt`) values (48,'VA','Virginia');
insert into `state`(`state_id`,`state_cd`,`name_txt`) values (49,'WA','Washington');
insert into `state`(`state_id`,`state_cd`,`name_txt`) values (50,'WV','West Virginia');
insert into `state`(`state_id`,`state_cd`,`name_txt`) values (51,'WI','Wisconsin');
insert into `state`(`state_id`,`state_cd`,`name_txt`) values (52,'WY','Wyoming');
insert into `state`(`state_id`,`state_cd`,`name_txt`) values (53,'BC','British Columbia');
