use cog;
delete from cog.link;
insert into cog.link(`id`,`name`,`url`,`sort_order`) values (1,'Church of God Evening Light','http://churchofgodeveninglight.com/',0);
insert into cog.link(`id`,`name`,`url`,`sort_order`) values (2,'Church of God Preaching','http://churchofgodpreaching.com',5);
insert into cog.link(`id`,`name`,`url`,`sort_order`) values (3,'Church of God Singing','http://churchofgodsinging.com',10);
insert into cog.link(`id`,`name`,`url`,`sort_order`) values (4,'The Gospel Truth','http://www.thegospeltruth.org/',15);
insert into cog.link(`id`,`name`,`url`,`sort_order`) values (5,'Africa Mission','https://www.africamission.com/',20);
insert into cog.link(`id`,`name`,`url`,`sort_order`) values (6,'Kenya Orphanage','https://www.facebook.com/hurumadolororphanage',25);
insert into cog.link(`id`,`name`,`url`,`sort_order`) values (7,'Sunday School Literature','https://www.sundayschoolliterature.com/',30);
insert into cog.link(`id`,`name`,`url`,`sort_order`) values (8,'Quarterly Bible Lessons','http://churchofgodtoday.com/',35);
insert into cog.link(`id`,`name`,`url`,`sort_order`) values (9,'Evening Light Songs','http://www.eveninglightsongs.com/',40);
insert into cog.link(`id`,`name`,`url`,`sort_order`) values (10,'Monark Springs Recordings','http://www.monarkcampmeeting.org/',45);
insert into cog.link(`id`,`name`,`url`,`sort_order`) values (11,'Church of God Mission','http://churchofgodmission.com',50);
insert into cog.link(`id`,`name`,`url`,`sort_order`) values (12,'Church of God - Dallas, Texas','http://www.churchofgoddallas.org/',55);
insert into cog.link(`id`,`name`,`url`,`sort_order`) values (13,'Church of God, Pacoima','https://www.churchofgodpacoima.com/',60);
insert into cog.link(`id`,`name`,`url`,`sort_order`) values (14,'Church of God - Sapulpa Road','http://www.sapulpachurchofgod.com/',65);
insert into cog.link(`id`,`name`,`url`,`sort_order`) values (15,'Church of God - Neosho','http://churchofgodneosho.org/',70);
insert into cog.link(`id`,`name`,`url`,`sort_order`) values (16,'Monark Springs','http://MonarkSprings.com',75);
insert into cog.link(`id`,`name`,`url`,`sort_order`) values (17,'Online Bible Concordances','http://concordances.org/',80);
insert into cog.link(`id`,`name`,`url`,`sort_order`) values (18,'Bible Gateway - Online Bible w/audio','http://biblegateway.com/',85);
insert into cog.link(`id`,`name`,`url`,`sort_order`) values (19,'Quick Bible Search','http://quod.lib.umich.edu/k/kjv/simple.html',90);
insert into cog.link(`id`,`name`,`url`,`sort_order`) values (20,'Bible History','http://bible-history.com/',95);
insert into cog.link(`id`,`name`,`url`,`sort_order`) values (21,'Life and Epistles of Paul','http://www.biblestudy.org/apostlepaul/main.html',100);
insert into cog.link(`id`,`name`,`url`,`sort_order`) values (22,'Church of God - Oklahoma City','http://www.oklahomacitychurchofgod.com/',66);

commit;