
insert into `location_detail`(`location_detail_id`,`location_id`,`type_code`,`label`,`value`,`sort_order`) values (1,1,'header','Location','',0);
insert into `location_detail`(`location_detail_id`,`location_id`,`type_code`,`label`,`value`,`sort_order`) values (3,1,'text','Address:','8939 SE Tolbert St',1);
insert into `location_detail`(`location_detail_id`,`location_id`,`type_code`,`label`,`value`,`sort_order`) values (4,1,'text','City, State, Zip','Clackamas, OR 97015',2);
insert into `location_detail`(`location_detail_id`,`location_id`,`type_code`,`label`,`value`,`sort_order`) values (5,1,'header','Services','',3);
insert into `location_detail`(`location_detail_id`,`location_id`,`type_code`,`label`,`value`,`sort_order`) values (6,1,'text','Sunday School:','10:15 AM',4);
insert into `location_detail`(`location_detail_id`,`location_id`,`type_code`,`label`,`value`,`sort_order`) values (7,1,'text','Sunday Services:','11:15 AM, 3:00 PM',5);
insert into `location_detail`(`location_detail_id`,`location_id`,`type_code`,`label`,`value`,`sort_order`) values (9,1,'header','Contact Info:','',8);
insert into `location_detail`(`location_detail_id`,`location_id`,`type_code`,`label`,`value`,`sort_order`) values (10,1,'email','Email:','delwell2@yahoo.com',9);
insert into `location_detail`(`location_detail_id`,`location_id`,`type_code`,`label`,`value`,`sort_order`) values (11,1,'url','Web Site:','http://localhost/cog',10);
insert into `location_detail`(`location_detail_id`,`location_id`,`type_code`,`label`,`value`,`sort_order`) values (12,3,'header','Location','',0);
insert into `location_detail`(`location_detail_id`,`location_id`,`type_code`,`label`,`value`,`sort_order`) values (13,3,'text','Address:','',1);
insert into `location_detail`(`location_detail_id`,`location_id`,`type_code`,`label`,`value`,`sort_order`) values (14,3,'text','City, State, Zip:','',2);
insert into `location_detail`(`location_detail_id`,`location_id`,`type_code`,`label`,`value`,`sort_order`) values (15,3,'header','Services','',3);
insert into `location_detail`(`location_detail_id`,`location_id`,`type_code`,`label`,`value`,`sort_order`) values (16,3,'text','Sunday School:','9:45 AM',4);
insert into `location_detail`(`location_detail_id`,`location_id`,`type_code`,`label`,`value`,`sort_order`) values (17,3,'text','Sunday AM:','10:45 AM',5);
insert into `location_detail`(`location_detail_id`,`location_id`,`type_code`,`label`,`value`,`sort_order`) values (18,3,'text','Sunday PM:','6:00 PM',6);
insert into `location_detail`(`location_detail_id`,`location_id`,`type_code`,`label`,`value`,`sort_order`) values (19,3,'header','Contact Info:','',7);
insert into `location_detail`(`location_detail_id`,`location_id`,`type_code`,`label`,`value`,`sort_order`) values (20,3,'email','Email:','',9);
insert into `location_detail`(`location_detail_id`,`location_id`,`type_code`,`label`,`value`,`sort_order`) values (22,3,'text','Wednesday PM:','7:30',8);
insert into `location_detail`(`location_detail_id`,`location_id`,`type_code`,`label`,`value`,`sort_order`) values (23,4,'header','Location','',0);
insert into `location_detail`(`location_detail_id`,`location_id`,`type_code`,`label`,`value`,`sort_order`) values (24,4,'text','Address:','14810 Skelton Rd SE',1);
insert into `location_detail`(`location_detail_id`,`location_id`,`type_code`,`label`,`value`,`sort_order`) values (25,4,'text','City, State, Zip:','Jefferson, OR 97352',2);
insert into `location_detail`(`location_detail_id`,`location_id`,`type_code`,`label`,`value`,`sort_order`) values (26,4,'header','Services','',3);
insert into `location_detail`(`location_detail_id`,`location_id`,`type_code`,`label`,`value`,`sort_order`) values (27,4,'text','Sunday School:','9:45 AM',4);
insert into `location_detail`(`location_detail_id`,`location_id`,`type_code`,`label`,`value`,`sort_order`) values (28,4,'text','Sunday Services:','10:45 AM; 2:00 PM',5);
insert into `location_detail`(`location_detail_id`,`location_id`,`type_code`,`label`,`value`,`sort_order`) values (30,4,'header','Contact Info:','',8);
insert into `location_detail`(`location_detail_id`,`location_id`,`type_code`,`label`,`value`,`sort_order`) values (32,4,'url','Web Site:','http://oldchurchofgodrecordingseveninglight.com/',10);
insert into `location_detail`(`location_detail_id`,`location_id`,`type_code`,`label`,`value`,`sort_order`) values (33,4,'text','Wednesday PM:','7:30',7);
insert into `location_detail`(`location_detail_id`,`location_id`,`type_code`,`label`,`value`,`sort_order`) values (34,5,'header','Location','',0);
insert into `location_detail`(`location_detail_id`,`location_id`,`type_code`,`label`,`value`,`sort_order`) values (35,5,'text','Address:','8500 Frankoma Road',1);
insert into `location_detail`(`location_detail_id`,`location_id`,`type_code`,`label`,`value`,`sort_order`) values (36,5,'text','City, State, Zip:','Sapulpa, OK',2);
insert into `location_detail`(`location_detail_id`,`location_id`,`type_code`,`label`,`value`,`sort_order`) values (37,5,'header','Services','',3);
insert into `location_detail`(`location_detail_id`,`location_id`,`type_code`,`label`,`value`,`sort_order`) values (38,5,'text','Sunday School:','9:45 AM',4);
insert into `location_detail`(`location_detail_id`,`location_id`,`type_code`,`label`,`value`,`sort_order`) values (39,5,'text','Sunday Services:','10:45 AM; 6:00 PM',5);
insert into `location_detail`(`location_detail_id`,`location_id`,`type_code`,`label`,`value`,`sort_order`) values (40,5,'text','Sunday PM:','6:00 PM',6);
insert into `location_detail`(`location_detail_id`,`location_id`,`type_code`,`label`,`value`,`sort_order`) values (41,5,'header','Contact Info:','',8);
insert into `location_detail`(`location_detail_id`,`location_id`,`type_code`,`label`,`value`,`sort_order`) values (43,5,'url','Web Site:','http://www.sapulpachurchofgod.com/',10);
insert into `location_detail`(`location_detail_id`,`location_id`,`type_code`,`label`,`value`,`sort_order`) values (44,5,'text','Wednesday PM:','7:00',7);
insert into `location_detail`(`location_detail_id`,`location_id`,`type_code`,`label`,`value`,`sort_order`) values (45,1,'text','Wednesday PM:','7:15 PM',7);
insert into `location_detail`(`location_detail_id`,`location_id`,`type_code`,`label`,`value`,`sort_order`) values (46,6,'header','Location','',0);
insert into `location_detail`(`location_detail_id`,`location_id`,`type_code`,`label`,`value`,`sort_order`) values (47,6,'text','Address:','18762 Linden Drive',1);
insert into `location_detail`(`location_detail_id`,`location_id`,`type_code`,`label`,`value`,`sort_order`) values (48,6,'text','City, State, Zip:','Neosho, MO 64850',2);
insert into `location_detail`(`location_detail_id`,`location_id`,`type_code`,`label`,`value`,`sort_order`) values (49,6,'header','Services','',3);
insert into `location_detail`(`location_detail_id`,`location_id`,`type_code`,`label`,`value`,`sort_order`) values (50,6,'text','Sunday School:','9:45 AM',4);
insert into `location_detail`(`location_detail_id`,`location_id`,`type_code`,`label`,`value`,`sort_order`) values (51,6,'text','Sunday Services:','10:45 AM; 6:30 PM',5);
insert into `location_detail`(`location_detail_id`,`location_id`,`type_code`,`label`,`value`,`sort_order`) values (53,6,'header','Contact Info:','',8);
insert into `location_detail`(`location_detail_id`,`location_id`,`type_code`,`label`,`value`,`sort_order`) values (55,6,'url','Web Site:','http://www.churchofgodneosho.org/',10);
insert into `location_detail`(`location_detail_id`,`location_id`,`type_code`,`label`,`value`,`sort_order`) values (56,6,'text','Wednesday PM:','7:00 PM',7);
insert into `location_detail`(`location_detail_id`,`location_id`,`type_code`,`label`,`value`,`sort_order`) values (68,7,'header','Location','',0);
insert into `location_detail`(`location_detail_id`,`location_id`,`type_code`,`label`,`value`,`sort_order`) values (69,7,'text','Address:','',1);
insert into `location_detail`(`location_detail_id`,`location_id`,`type_code`,`label`,`value`,`sort_order`) values (70,7,'text','City, State, Zip:','',2);
insert into `location_detail`(`location_detail_id`,`location_id`,`type_code`,`label`,`value`,`sort_order`) values (71,7,'header','Services','',3);
insert into `location_detail`(`location_detail_id`,`location_id`,`type_code`,`label`,`value`,`sort_order`) values (72,7,'text','Sunday School:','9:45 AM',4);
insert into `location_detail`(`location_detail_id`,`location_id`,`type_code`,`label`,`value`,`sort_order`) values (73,7,'text','Sunday Services:','10:45 AM; 6:00 PM',5);
insert into `location_detail`(`location_detail_id`,`location_id`,`type_code`,`label`,`value`,`sort_order`) values (74,7,'header','Contact Info:','',7);
insert into `location_detail`(`location_detail_id`,`location_id`,`type_code`,`label`,`value`,`sort_order`) values (75,7,'text','Pastor:','Bro. Michael Smith (417) 725-5769',8);
insert into `location_detail`(`location_detail_id`,`location_id`,`type_code`,`label`,`value`,`sort_order`) values (76,7,'url','Web Site:','http://www.churchofgodeveninglight.com',9);
insert into `location_detail`(`location_detail_id`,`location_id`,`type_code`,`label`,`value`,`sort_order`) values (77,7,'text','Wednesday PM:','7:30',6);
insert into `location_detail`(`location_detail_id`,`location_id`,`type_code`,`label`,`value`,`sort_order`) values (78,8,'header','Location','',0);
insert into `location_detail`(`location_detail_id`,`location_id`,`type_code`,`label`,`value`,`sort_order`) values (79,8,'text','Address:','5900 NE 23rd St',1);
insert into `location_detail`(`location_detail_id`,`location_id`,`type_code`,`label`,`value`,`sort_order`) values (80,8,'text','City, State, Zip:','Oklahoma CIty, OK',2);
insert into `location_detail`(`location_detail_id`,`location_id`,`type_code`,`label`,`value`,`sort_order`) values (81,8,'header','Services','',3);
insert into `location_detail`(`location_detail_id`,`location_id`,`type_code`,`label`,`value`,`sort_order`) values (82,8,'text','Sunday School:','9:45 AM',4);
insert into `location_detail`(`location_detail_id`,`location_id`,`type_code`,`label`,`value`,`sort_order`) values (83,8,'text','Sunday Services:','10:45 AM; 6:00 PM',5);
insert into `location_detail`(`location_detail_id`,`location_id`,`type_code`,`label`,`value`,`sort_order`) values (84,8,'header','Contact Info:','',7);
insert into `location_detail`(`location_detail_id`,`location_id`,`type_code`,`label`,`value`,`sort_order`) values (85,8,'email','Phone:','Bro. Loren Busbee (405) 478-3860',8);
insert into `location_detail`(`location_detail_id`,`location_id`,`type_code`,`label`,`value`,`sort_order`) values (86,8,'url','Chapel Phone:','(405) 427-1223',9);
insert into `location_detail`(`location_detail_id`,`location_id`,`type_code`,`label`,`value`,`sort_order`) values (87,8,'text','Wednesday PM:','7:30',6);
