
insert into `location`(`location_id`,`name_txt`,`description`,`address`,`city_id`,`active_ind`,`google_url`) values (1,'Clackamas','Clackamas Congregation','Tolbert Street',1,'N','<iframe width="480" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?source=s_q&hl=en&geocode=&q=8939+Southeast+Tolbert+Street,+Clackamas,+OR&t=h&ie=UTF8&output=embed"></iframe><br />');
insert into `location`(`location_id`,`name_txt`,`description`,`address`,`city_id`,`active_ind`,`google_url`) values (2,'Gladstone','The Gladstone chapel','Dartmouth',3,'Y','<iframe width="480" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?source=s_q&hl=en&geocode=&q=255+E+Exeter+Street,+Gladstone,+OR+97027&t=h&ie=UTF8&output=embed"></iframe>');
insert into `location`(`location_id`,`name_txt`,`description`,`address`,`city_id`,`active_ind`,`google_url`) values (3,'Chilliwack',null,null,4,'N',null);
insert into `location`(`location_id`,`name_txt`,`description`,`address`,`city_id`,`active_ind`,`google_url`) values (4,'Jefferson','Jefferson Oregon Campgrounds','14810 Skelton Rd SE, Jefferson, OR 97352',2,'Y','<iframe width="480" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=14810+Skelton+Rd+SE+Jefferson,+OR&amp;&t=h&ie=UTF8&output=embed"></iframe>');
insert into `location`(`location_id`,`name_txt`,`description`,`address`,`city_id`,`active_ind`,`google_url`) values (5,'Sapulpa','Sapulpa Congregation','8500 S. Frankoma Road',5,'Y','<iframe width="480" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=8500+South+Frankoma+Road,+Sapulpa,+OK&amp;&t=h&ie=UTF8&output=embed"></iframe>');
insert into `location`(`location_id`,`name_txt`,`description`,`address`,`city_id`,`active_ind`,`google_url`) values (6,'Neosho','Neosho, Missouri','18762 Linden Drive, Neosho, MO 64850',6,'Y','<iframe width="480" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=18762+Linden+Drive+Neosho,+MO+64850&amp;&t=h&ie=UTF8&output=embed"></iframe>');
insert into `location`(`location_id`,`name_txt`,`description`,`address`,`city_id`,`active_ind`,`google_url`) values (7,'Springfield','Springfield, MO','444 E. Evergreen',8,'Y','<iframe width="480" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=444+E.+Evergreen+Springfield,+MO&amp;&t=h&ie=UTF8&output=embed"></iframe>');
insert into `location`(`location_id`,`name_txt`,`description`,`address`,`city_id`,`active_ind`,`google_url`) values (8,'Oklahoma City',null,'5900 N.E. 23rd St.',9,'Y','<iframe width="480" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?f=q&source=s_q&hl=en&geocode=&q=6438+Northeast+23rd+Street,+Oklahoma+City,+OK&t=h&ie=UTF8&output=embed"></iframe>');
