
insert into `scripture`(`scripture_id`,`scripture_txt`,`chapter_verse`) values (1,'For I know the thoughts that I think toward you, saith the Lord, thoughts of peace, and not of evil, to give you an expected end.','Jeremiah 29:11');
insert into `scripture`(`scripture_id`,`scripture_txt`,`chapter_verse`) values (2,'Come unto me, all ye that labour and are heavy laden, and I will give you rest.Take my yoke upon you, and learn of me; for I am meek and lowly in heart: and ye shall find rest unto your souls.For my yoke is easy, and my burden is light.','Matthew 11:28-30');
insert into `scripture`(`scripture_id`,`scripture_txt`,`chapter_verse`) values (3,'Be careful for nothing; but in every thing by prayer and supplication with thanksgiving let your requests be made known unto God. And the peace of God, which passeth all understanding, shall keep your hearts and minds through Christ Jesus.','Philippians 4:6-7');
insert into `scripture`(`scripture_id`,`scripture_txt`,`chapter_verse`) values (4,'But he was wounded for our transgressions,he was bruised for our iniquities:the chastisement of our peace was upon him;and with his stripes we are healed.','Isaiah 53:5');
insert into `scripture`(`scripture_id`,`scripture_txt`,`chapter_verse`) values (5,'Therefore if any man be in Christ, he is a new creature: old things are passed away; behold, all things are become new.','2 Corinthians 5:17');
insert into `scripture`(`scripture_id`,`scripture_txt`,`chapter_verse`) values (6,'For God so loved the world, that he gave his only begotten Son, that whosoever believeth in him should not perish, but have everlasting life.','John 3:16');
insert into `scripture`(`scripture_id`,`scripture_txt`,`chapter_verse`) values (7,'He maketh the storm a calm,so that the waves thereof are still.','Psalms 107:29');
insert into `scripture`(`scripture_id`,`scripture_txt`,`chapter_verse`) values (8,'Brethren, I count not myself to have apprehended: but this one thing I do, forgetting those things which are behind, and reaching forth unto those things which are before, I press toward the mark for the prize of the high calling of God in Christ Jesus.','Philippians 3:13-14');
insert into `scripture`(`scripture_id`,`scripture_txt`,`chapter_verse`) values (9,'I beseech you therefore, brethren, by the mercies of God, that ye present your bodies a living sacrifice, holy, acceptable unto God, which is your reasonable service. And be not conformed to this world: but be ye transformed by the renewing of your mind, that ye may prove what is that good, and acceptable, and perfect, will of God.','Romans 12:1-2');
insert into `scripture`(`scripture_id`,`scripture_txt`,`chapter_verse`) values (10,'Humble yourselves therefore under the mighty hand of God, that he may exalt you in due time: Casting all your care upon him; for he careth for you.','1 Peter 5:6-7');
insert into `scripture`(`scripture_id`,`scripture_txt`,`chapter_verse`) values (11,'A new heart also will I give you, and a new spirit will I put within you: and I will take away the stony heart out of your flesh, and I will give you an heart of flesh. And I will put my spirit within you, and cause you to walk in my statutes, and ye shall keep my judgments, and do them.','Ezekiel 36:26-27');
insert into `scripture`(`scripture_id`,`scripture_txt`,`chapter_verse`) values (12,'Thou wilt keep him in perfect peace,whose mind is stayed on thee:because he trusteth in thee.','Isaiah 26:3');
insert into `scripture`(`scripture_id`,`scripture_txt`,`chapter_verse`) values (13,'Trust in the Lord, and do good;so shalt thou dwell in the land, and verily thou shalt be fed.Delight thyself also in the Lord;and he shall give thee the desires of thine heart.','Psalms 37:3-4');
insert into `scripture`(`scripture_id`,`scripture_txt`,`chapter_verse`) values (14,'Let this mind be in you, which was also in Christ Jesus: Who, being in the form of God, thought it not robbery to be equal with God: But made himself of no reputation, and took upon him the form of a servant, and was made in the likeness of men','Philippians 2:5-7');
insert into `scripture`(`scripture_id`,`scripture_txt`,`chapter_verse`) values (15,'For the eyes of the Lord run to and fro throughout the whole earth, to shew himself strong in the behalf of them whose heart is perfect toward him.','2 Chronicles 16:9');
insert into `scripture`(`scripture_id`,`scripture_txt`,`chapter_verse`) values (16,'I can do all things through Christ which strengtheneth me.','Philippians 4:13');
insert into `scripture`(`scripture_id`,`scripture_txt`,`chapter_verse`) values (17,'What shall we say then? Shall we continue in sin, that grace may abound? God forbid. How shall we, that are dead to sin, live any longer therein?','Romans 6:1-2');
insert into `scripture`(`scripture_id`,`scripture_txt`,`chapter_verse`) values (18,'There is therefore now no condemnation to them which are in Christ Jesus, who walk not after the flesh, but after the Spirit. For the law of the Spirit of life in Christ Jesus hath made me free from the law of sin and death.','Romans 8:1-2');
insert into `scripture`(`scripture_id`,`scripture_txt`,`chapter_verse`) values (19,'And we know that all things work together for good to them that love God, to them who are the called according to his purpose.','Romans 8:28');
insert into `scripture`(`scripture_id`,`scripture_txt`,`chapter_verse`) values (20,'What shall we then say to these things? If God be for us, who can be against us? He that spared not his own Son, but delivered him up for us all, how shall he not with him also freely give us all things?','Romans 8:31-32');
insert into `scripture`(`scripture_id`,`scripture_txt`,`chapter_verse`) values (21,'Forasmuch then as the children are partakers of flesh and blood, he also himself likewise took part of the same; that through death he might destroy him that had the power of death, that is, the devil; And deliver them who through fear of death were all their lifetime subject to bondage.','Hebrews 2:14-15');
insert into `scripture`(`scripture_id`,`scripture_txt`,`chapter_verse`) values (22,'Wherefore in all things it behoved him to be made like unto his brethren, that he might be a merciful and faithful high priest in things pertaining to God, to make reconciliation for the sins of the people. For in that he himself hath suffered being tempted, he is able to succour them that are tempted.','Hebrews 2:17-18');
insert into `scripture`(`scripture_id`,`scripture_txt`,`chapter_verse`) values (23,'For we have not an high priest which cannot be touched with the feeling of our infirmities; but was in all points tempted like as we are, yet without sin. Let us therefore come boldly unto the throne of grace, that we may obtain mercy, and find grace to help in time of need.','Hebrews 4:15-16');
insert into `scripture`(`scripture_id`,`scripture_txt`,`chapter_verse`) values (24,'For the word of God is quick, and powerful, and sharper than any twoedged sword, piercing even to the dividing asunder of soul and spirit, and of the joints and marrow, and is a discerner of the thoughts and intents of the heart. Neither is there any creature that is not manifest in his sight: but all things are naked and opened unto the eyes of him with whom we have to do.','Hebrews 4:12-13');
insert into `scripture`(`scripture_id`,`scripture_txt`,`chapter_verse`) values (25,'Wherefore he is able also to save them to the uttermost that come unto God by him, seeing he ever liveth to make intercession for them.','Hebrews 7:25');
insert into `scripture`(`scripture_id`,`scripture_txt`,`chapter_verse`) values (26,'For this is the covenant that I will make with the house of Israel after those days, saith the Lord; I will put my laws into their mind, and write them in their hearts: and I will be to them a God, and they shall be to me a people:','Hebrews 8:10');
insert into `scripture`(`scripture_id`,`scripture_txt`,`chapter_verse`) values (27,'For if the blood of bulls and of goats, and the ashes of an heifer sprinkling the unclean, sanctifieth to the purifying of the flesh: How much more shall the blood of Christ, who through the eternal Spirit offered himself without spot to God, purge your conscience from dead works to serve the living God?','Hebrews 9:13-14');
insert into `scripture`(`scripture_id`,`scripture_txt`,`chapter_verse`) values (28,'Now faith is the substance of things hoped for, the evidence of things not seen.','Hebrews 11:1');
insert into `scripture`(`scripture_id`,`scripture_txt`,`chapter_verse`) values (29,'But without faith it is impossible to please him: for he that cometh to God must believe that he is, and that he is a rewarder of them that diligently seek him.','Hebrews 11:6');
insert into `scripture`(`scripture_id`,`scripture_txt`,`chapter_verse`) values (30,'And as it is appointed unto men once to die, but after this the judgment: So Christ was once offered to bear the sins of many; and unto them that look for him shall he appear the second time without sin unto salvation.','Hebrews 9:27-28');
insert into `scripture`(`scripture_id`,`scripture_txt`,`chapter_verse`) values (31,'Wherefore seeing we also are compassed about with so great a cloud of witnesses, let us lay aside every weight, and the sin which doth so easily beset us, and let us run with patience the race that is set before us, Looking unto Jesus the author and finisher of our faith; who for the joy that was set before him endured the cross, despising the shame, and is set down at the right hand of the throne of God.','Hebrews 12:1-2');
insert into `scripture`(`scripture_id`,`scripture_txt`,`chapter_verse`) values (32,'But ye are come unto mount Sion, and unto the city of the living God, the heavenly Jerusalem, and to an innumerable company of angels, To the general assembly and church of the firstborn, which are written in heaven, and to God the Judge of all, and to the spirits of just men made perfect, And to Jesus the mediator of the new covenant, and to the blood of sprinkling, that speaketh better things than that of Abel.','Hebrews 12:22-24');
insert into `scripture`(`scripture_id`,`scripture_txt`,`chapter_verse`) values (33,'Wherefore Jesus also, that he might sanctify the people with his own blood, suffered without the gate. Let us go forth therefore unto him without the camp, bearing his reproach. For here have we no continuing city, but we seek one to come.','Hebrews 13:12-14');
insert into `scripture`(`scripture_id`,`scripture_txt`,`chapter_verse`) values (34,'My brethren, count it all joy when ye fall into divers temptations; Knowing this, that the trying of your faith worketh patience. But let patience have her perfect work, that ye may be perfect and entire, wanting nothing.','James 1:2-4');
insert into `scripture`(`scripture_id`,`scripture_txt`,`chapter_verse`) values (35,'Blessed is the man that endureth temptation: for when he is tried, he shall receive the crown of life, which the Lord hath promised to them that love him.','James 1:12');
insert into `scripture`(`scripture_id`,`scripture_txt`,`chapter_verse`) values (36,'If any man among you seem to be religious, and bridleth not his tongue, but deceiveth his own heart, this man''s religion is vain. Pure religion and undefiled before God and the Father is this, To visit the fatherless and widows in their affliction, and to keep himself unspotted from the world.','James 1:26-27');
insert into `scripture`(`scripture_id`,`scripture_txt`,`chapter_verse`) values (37,'What doth it profit, my brethren, though a man say he hath faith, and have not works? can faith save him? If a brother or sister be naked, and destitute of daily food, And one of you say unto them, Depart in peace, be ye warmed and filled; notwithstanding ye give them not those things which are needful to the body; what doth it profit? Even so faith, if it hath not works, is dead, being alone.','James 2:14-17');
insert into `scripture`(`scripture_id`,`scripture_txt`,`chapter_verse`) values (38,'Is any sick among you? let him call for the elders of the church; and let them pray over him, anointing him with oil in the name of the Lord: And the prayer of faith shall save the sick, and the Lord shall raise him up; and if he have committed sins, they shall be forgiven him.','James 5:14-15');
insert into `scripture`(`scripture_id`,`scripture_txt`,`chapter_verse`) values (39,'Wherefore laying aside all malice, and all guile, and hypocrisies, and envies, and all evil speakings, As newborn babes, desire the sincere milk of the word, that ye may grow thereby: If so be ye have tasted that the Lord is gracious.','1 Peter 2:1-3');
insert into `scripture`(`scripture_id`,`scripture_txt`,`chapter_verse`) values (40,'For this is thankworthy, if a man for conscience toward God endure grief, suffering wrongfully. For what glory is it, if, when ye be buffeted for your faults, ye shall take it patiently? but if, when ye do well, and suffer for it, ye take it patiently, this is acceptable with God.','1 Peter 2:19-20');
insert into `scripture`(`scripture_id`,`scripture_txt`,`chapter_verse`) values (41,'But they that wait upon the Lord shall renew their strength;they shall mount up with wings as eagles;they shall run, and not be weary;and they shall walk, and not faint.','Isaiah 40:31');
insert into `scripture`(`scripture_id`,`scripture_txt`,`chapter_verse`) values (42,'And in the days of these kings shall the God of heaven set up a kingdom, which shall never be destroyed: and the kingdom shall not be left to other people, but it shall break in pieces and consume all these kingdoms, and it shall stand for ever.','Daniel 2:44');
insert into `scripture`(`scripture_id`,`scripture_txt`,`chapter_verse`) values (43,'He hath shewed thee, O man, what is good;and what doth the Lord require of thee,but to do justly, and to love mercy,and to walk humbly with thy God?','Micah 6:8');
insert into `scripture`(`scripture_id`,`scripture_txt`,`chapter_verse`) values (44,'And it shall come to pass afterward,that I will pour out my spirit upon all flesh;and your sons and your daughters shall prophesy,your old men shall dream dreams,your young men shall see visions:And also upon the servants and upon the handmaidsin those days will I pour out my spirit.','Joel 2:28-29');
insert into `scripture`(`scripture_id`,`scripture_txt`,`chapter_verse`) values (45,'But who may abide the day of his coming?and who shall stand when he appeareth?for he is like a refiner''s fire, and like fullers ''soap''And he shall sit as a refiner and purifier of silver:and he shall purify the sons of Levi, and purge them as gold and silver, that they may offer unto the Lord an offering in righteousness.','Malachi 3:2-3');
insert into `scripture`(`scripture_id`,`scripture_txt`,`chapter_verse`) values (46,'Then they that feared the Lord spake often one to another:and the Lord hearkened, and heard it,and a book of remembrance was written before himfor them that feared the Lord, and that thought upon his name.','Malachi 3:16');
insert into `scripture`(`scripture_id`,`scripture_txt`,`chapter_verse`) values (47,'Thus saith the Lord,The heaven is my throne, and the earth is my footstool:where is the house that ye build unto me?and where is the place of my rest?For all those things hath mine hand made,and all those things have been, saith the Lord:but to this man will I look,even to him that is poor and of a contrite spirit,and trembleth at my word.','Isaiah 66:1-2');
insert into `scripture`(`scripture_id`,`scripture_txt`,`chapter_verse`) values (48,'Is it such a fast that I have chosen?a day for a man to afflict his soul?is it to bow down his head as a bulrush,and to spread sackcloth and ashes under him?wilt thou call this a fast,and an acceptable day to the Lord?Is not this the fast that I have chosen?to loose the bands of wickedness,to undo the heavy burdens,and to let the oppressed go free,and that ye break every yoke?','Isaiah 58:5-6');
insert into `scripture`(`scripture_id`,`scripture_txt`,`chapter_verse`) values (49,'Seek ye the Lord while he may be found,call ye upon him while he is near:Let the wicked forsake his way,and the unrighteous man his thoughts:and let him return unto the Lord, and he will have mercy upon him; and to our God, for he will abundantly pardon.','Isaiah 55:6-7');
insert into `scripture`(`scripture_id`,`scripture_txt`,`chapter_verse`) values (50,'Ho, every one that thirsteth, come ye to the waters,and he that hath no money;come ye, buy, and eat;yea, come, buy wine and milk without money and without price.Wherefore do ye spend money for that which is not bread?and your labour for that which satisfieth not?hearken diligently unto me, and eat ye that which is good,and let your soul delight itself in fatness','Isaiah 55:1-2');
insert into `scripture`(`scripture_id`,`scripture_txt`,`chapter_verse`) values (51,'For this is as the waters of Noah unto me:for as I have sworn that the waters of Noah should no more go over the earth;so have I sworn that I would not be wroth with thee, nor rebuke thee.For the mountains shall depart,and the hills be removed;but my kindness shall not depart from thee,neither shall the covenant of my peace be removed,saith the Lord that hath mercy on thee.','Isaiah 54:9-10');
insert into `scripture`(`scripture_id`,`scripture_txt`,`chapter_verse`) values (52,'When I consider thy heavens, the work of thy fingers,the moon and the stars, which thou hast ordained;What is man, that thou art mindful of him?and the son of man, that thou visitest him?','Psalms 8:3-4');
insert into `scripture`(`scripture_id`,`scripture_txt`,`chapter_verse`) values (53,'Lord, who shall abide in thy tabernacle?who shall dwell in thy holy hill? He that walketh uprightly, and worketh righteousness,and speaketh the truth in his heart.He that backbiteth not with his tongue,nor doeth evil to his neighbour,nor taketh up a reproach against his neighbour.','Psalms 15:1-3');
insert into `scripture`(`scripture_id`,`scripture_txt`,`chapter_verse`) values (54,'As for God, his way is perfect:the word of the Lord is tried:he is a buckler to all those that trust in him.For who is God save the Lord?or who is a rock save our God?','Psalms 18:30-31');
insert into `scripture`(`scripture_id`,`scripture_txt`,`chapter_verse`) values (55,'I will love thee, O Lord, my strength.The Lord is my rock, and my fortress, and my deliverer;my God, my strength, in whom I will trust;my buckler, and the horn of my salvation, and my high tower.','Psalms 18:1-2');
insert into `scripture`(`scripture_id`,`scripture_txt`,`chapter_verse`) values (56,'The law of the Lord is perfect, converting the soul:the testimony of the Lord is sure, making wise the simple.The statutes of the Lord are right, rejoicing the heart:the commandment of the Lord is pure, enlightening the eyes.The fear of the Lord is clean, enduring for ever:the judgments of the Lord are true and righteous altogether.','Psalms 19:7-9');
insert into `scripture`(`scripture_id`,`scripture_txt`,`chapter_verse`) values (57,'The Lord is my shepherd; I shall not want.He maketh me to lie down in green pastures:he leadeth me beside the still waters.','Psalms 23:1-2');
insert into `scripture`(`scripture_id`,`scripture_txt`,`chapter_verse`) values (58,'Yea, though I walk through the valley of the shadow of death,I will fear no evil: for thou art with me;thy rod and thy staff they comfort me.','Psalms 23:4');
insert into `scripture`(`scripture_id`,`scripture_txt`,`chapter_verse`) values (59,'One thing have I desired of the Lord, that will I seek after;that I may dwell in the house of the Lord all the days of my life,to behold the beauty of the Lord, and to enquire in his temple.','Psalms 27:4');
insert into `scripture`(`scripture_id`,`scripture_txt`,`chapter_verse`) values (60,'Be of good courage, and he shall strengthen your heart,all ye that hope in the Lord.','Psalms 31:24');
insert into `scripture`(`scripture_id`,`scripture_txt`,`chapter_verse`) values (61,'I sought the Lord, and he heard me,and delivered me from all my fears.They looked unto him, and were lightened:and their faces were not ashamed.This poor man cried, and the Lord heard him,and saved him out of all his troubles.','Psalms 34:4-6');
insert into `scripture`(`scripture_id`,`scripture_txt`,`chapter_verse`) values (62,'The Lord is nigh unto them that are of a broken heart;and saveth such as be of a contrite spirit.','Psalms 34:18');
insert into `scripture`(`scripture_id`,`scripture_txt`,`chapter_verse`) values (63,'I have been young, and now am old;yet have I not seen the righteous forsaken,nor his seed begging bread.','Psalms 37:25');
insert into `scripture`(`scripture_id`,`scripture_txt`,`chapter_verse`) values (64,'Mark the perfect man, and behold the upright:for the end of that man is peace.','Psalms 37:37');
insert into `scripture`(`scripture_id`,`scripture_txt`,`chapter_verse`) values (65,'It is of the Lord ''s mercies that we are not consumed, because his compassions fail not.They are new every morning: great is thy faithfulness.','Lamentations 3:22-23');
insert into `scripture`(`scripture_id`,`scripture_txt`,`chapter_verse`) values (66,'Let us hear the conclusion of the whole matter: Fear God, and keep his commandments: for this is the whole duty of man. For God shall bring every work into judgment, with every secret thing, whether it be good, or whether it be evil.','Ecclesiastes 12:13-14');
insert into `scripture`(`scripture_id`,`scripture_txt`,`chapter_verse`) values (67,'Because sentence against an evil work is not executed speedily, therefore the heart of the sons of men is fully set in them to do evil.','Ecclesiastes 8:11');
insert into `scripture`(`scripture_id`,`scripture_txt`,`chapter_verse`) values (68,'For thus saith the high and lofty Onethat inhabiteth eternity, whose name is Holy;I dwell in the high and holy place,with him also that is of a contrite and humble spirit,to revive the spirit of the humble,and to revive the heart of the contrite ones.','Isaiah 57:15');
insert into `scripture`(`scripture_id`,`scripture_txt`,`chapter_verse`) values (69,'He hath made every thing beautiful in his time: also he hath set the world in their heart, so that no man can find out the work that God maketh from the beginning to the end.','Ecclesiastes 3:11');
insert into `scripture`(`scripture_id`,`scripture_txt`,`chapter_verse`) values (70,'Thus saith the Lord,Let not the wise man glory in his wisdom,neither let the mighty man glory in his might, let not the rich man glory in his riches:But let him that glorieth glory in this,that he understandeth and knoweth me,that I am the Lord which exercise lovingkindness, judgment, and righteousness, in the earth:for in these things I delight, saith the Lord.','Jeremiah 9:23-24');
insert into `scripture`(`scripture_id`,`scripture_txt`,`chapter_verse`) values (71,'The heart is deceitful above all things, and desperately wicked: who can know it? I the Lord search the heart, I try the reins, even to give every man according to his ways, and according to the fruit of his doings.','Jeremiah 17:9-10');
insert into `scripture`(`scripture_id`,`scripture_txt`,`chapter_verse`) values (72,'And in that day there shall be a root of Jesse,which shall stand for an ensign of the people;to it shall the Gentiles seek:and his rest shall be glorious.','Isaiah 11:10');
insert into `scripture`(`scripture_id`,`scripture_txt`,`chapter_verse`) values (73,'Behold, I go forward, but he is not there;and backward, but I cannot perceive him:On the left hand, where he doth work, but I cannot behold him:he hideth himself on the right hand, that I cannot see him:But he knoweth the way that I take:when he hath tried me, I shall come forth as gold.','Job 23:8-10');
insert into `scripture`(`scripture_id`,`scripture_txt`,`chapter_verse`) values (74,'Then Nebuchadnezzar the king was astonied, and rose up in haste, and spake, and said unto his counsellors, Did not we cast three men bound into the midst of the fire? They answered and said unto the king, True, O king. He answered and said, Lo, I see four men loose, walking in the midst of the fire, and they have no hurt; and the form of the fourth is like the Son of God.','Daniel 3:24-25');
insert into `scripture`(`scripture_id`,`scripture_txt`,`chapter_verse`) values (75,'Marvel not that I said unto thee, Ye must be born again. The wind bloweth where it listeth, and thou hearest the sound thereof, but canst not tell whence it cometh, and whither it goeth: so is every one that is born of the Spirit.','John 3:7-8');
insert into `scripture`(`scripture_id`,`scripture_txt`,`chapter_verse`) values (76,'He must increase, but I must decrease.','John 3:30');
insert into `scripture`(`scripture_id`,`scripture_txt`,`chapter_verse`) values (77,'But the hour cometh, and now is, when the true worshippers shall worship the Father in spirit and in truth: for the Father seeketh such to worship him. God is a Spirit: and they that worship him must worship him in spirit and in truth.','John 4:23-24');
insert into `scripture`(`scripture_id`,`scripture_txt`,`chapter_verse`) values (78,'Verily, verily, I say unto you, He that heareth my word, and believeth on him that sent me, hath everlasting life, and shall not come into condemnation; but is passed from death unto life. Verily, verily, I say unto you, The hour is coming, and now is, when the dead shall hear the voice of the Son of God: and they that hear shall live.','John 5:24-25');
insert into `scripture`(`scripture_id`,`scripture_txt`,`chapter_verse`) values (79,'Search the scriptures; for in them ye think ye have eternal life: and they are they which testify of me.','John 5:39');
insert into `scripture`(`scripture_id`,`scripture_txt`,`chapter_verse`) values (80,'Then spake Jesus again unto them, saying, I am the light of the world: he that followeth me shall not walk in darkness, but shall have the light of life.','John 8:12');
insert into `scripture`(`scripture_id`,`scripture_txt`,`chapter_verse`) values (81,'Then said Jesus to those Jews which believed on him, If ye continue in my word, then are ye my disciples indeed;  And ye shall know the truth, and the truth shall make you free.','John 8:31-32');
insert into `scripture`(`scripture_id`,`scripture_txt`,`chapter_verse`) values (82,'I am the door: by me if any man enter in, he shall be saved, and shall go in and out, and find pasture. The thief cometh not, but for to steal, and to kill, and to destroy: I am come that they might have life, and that they might have it more abundantly.','John 10:9-10');
insert into `scripture`(`scripture_id`,`scripture_txt`,`chapter_verse`) values (83,'To him the porter openeth; and the sheep hear his voice: and he calleth his own sheep by name, and leadeth them out. And when he putteth forth his own sheep, he goeth before them, and the sheep follow him: for they know his voice.','John 10:3-4');
